# IMPORTING FILES

In [1]:
import pandas as pd
import os
import re

def convert_dir_to_csv(dir_path):
    files = os.listdir(dir_path)
    files.remove('list.csv')
    dataset_dict ={"category":[], "articles":[]}
    #f=open('/content/drive/MyDrive/News_Group/comp.graphics.txt','r+',encoding='latin1')
    

    # line=re.sub('\d','',line)
    # line=re.sub('.',' ',line)
   #line=re.sub('\d','',line)

    

    for i in files:
        with open(dir_path+'/'+i, 'r+',encoding='latin1') as f:
          line=f.read()
          line=' '.join(line.split())

          # re.sub(r'\n','',line)
          # re.sub(r'\t','',line)
          # re.sub('^From:$','',line)
          # re.sub('^News:$','',line)
          # re.sub(r'\d','',line)
          dataset_dict["articles"].append(line)
          dataset_dict["category"].append(i[:len(i)-4])
          df = pd.DataFrame(dataset_dict)

    return df
# print(convert_dir_to_csv('/content/drive/MyDrive/News_Group')[:10000])
dataframe = convert_dir_to_csv('20_NewsGroups')

# from google.colab import drive
# drive.mount('/content/drive')
# dataframe['articles'][0]

In [2]:
import requests
from bs4 import BeautifulSoup
url="https://basketballhq.com/basketball-articles-for-players"
r=requests.get(url)
htmlContent=r.content
soup = BeautifulSoup(htmlContent, 'html.parser')
i=0
f = open("test/rec.sport.baseball.txt", "w")
for data in soup.find_all("p"):
    print()
    if i<9 and i>2:
      sum = data.get_text()
      f.writelines(sum+'\n')
    if i>9:
      break      
    i+=1

f.close()

In [3]:
import requests
from bs4 import BeautifulSoup
url="https://www.sciencenews.org/article/black-hole-picture-magnetic-fields-event-horizon-telescope"
r=requests.get(url)
htmlContent=r.content
soup = BeautifulSoup(htmlContent, 'html.parser')
i=0
f = open("test/sci.space.txt", "w")
for data in soup.find_all("p"):
    print()
    if i<9 and i>2:
      sum = data.get_text()
      f.writelines(sum+'\n')
    if i>9:
      break      
    i+=1

f.close()

In [4]:
import pandas as pd
import os
import re

def convert_dir_to_csv(dir_path):
    files = os.listdir(dir_path)
    
    dataset_dict ={"category":[], "articles":[]}
    #f=open('/content/drive/MyDrive/News_Group/comp.graphics.txt','r+',encoding='latin1')
    

    # line=re.sub('\d','',line)
    # line=re.sub('.',' ',line)
   #line=re.sub('\d','',line)

    

    for i in files:
        with open(dir_path+'/'+i, 'r+',encoding='latin1') as f:
          line=f.read()
          line=' '.join(line.split())

          # re.sub(r'\n','',line)
          # re.sub(r'\t','',line)
          # re.sub('^From:$','',line)
          # re.sub('^News:$','',line)
          # re.sub(r'\d','',line)
          dataset_dict["articles"].append(line)
          dataset_dict["category"].append(i[:len(i)-4])
          df = pd.DataFrame(dataset_dict)

    return df
# print(convert_dir_to_csv('/content/drive/MyDrive/News_Group')[:10000])
testing = convert_dir_to_csv('test')

# from google.colab import drive
# drive.mount('/content/drive')
# dataframe['articles'][0]

In [5]:
dataframe

category  \
0                alt.atheism   
1              comp.graphics   
2    comp.os.ms-windows.misc   
3   comp.sys.ibm.pc.hardware   
4      comp.sys.mac.hardware   
5             comp.windows.x   
6               misc.forsale   
7                  rec.autos   
8            rec.motorcycles   
9         rec.sport.baseball   
10          rec.sport.hockey   
11                 sci.crypt   
12           sci.electronics   
13                   sci.med   
14                 sci.space   
15    soc.religion.christian   
16        talk.politics.guns   
17     talk.politics.mideast   
18        talk.politics.misc   
19        talk.religion.misc   

                                             articles  
0   From: mathew <mathew@mantis.co.uk> Subject: Al...  
1   From: lipman@oasys.dt.navy.mil (Robert Lipman)...  
2   Newsgroup: comp.os.ms-windows.misc document_id...  
3   Newsgroup: comp.sys.ibm.pc.hardware document_i...  
4   Newsgroup: comp.sys.mac.hardware document_id: ...  
5   Newsgroup: comp.windows.x document_id: 64830 F...  
6   Newsgroup: misc.forsale document_id: 70337 Fro...  
7   Newsgroup: rec.autos document_id: 101551 From:...  
8   Newsgroup: rec.motorcycles document_id: 101725...  
9   Newsgroup: rec.sport.baseball document_id: 100...  
10  Newsgroup: rec.sport.hockey document_id: 52550...  
11  Newsgroup: sci.crypt document_id: 14147 From: ...  
12  Newsgroup: sci.electronics document_id: 52434 ...  
13  Newsgroup: sci.med document_id: 57110 From: be...  
14  Newsgroup: sci.space document_id: 59497 From: ...  
15  Newsgroup: soc.religion.christian document_id:...  
16  Newsgroup: talk.politics.guns document_id: 532...  
17  Newsgroup: talk.politics.mideast document_id: ...  
18  Newsgroup: talk.politics.misc document_id: 124...  
19  Newsgroup: talk.religion.misc document_id: 827...

In [6]:
dataframe['articles']

0     From: mathew <mathew@mantis.co.uk> Subject: Al...
1     From: lipman@oasys.dt.navy.mil (Robert Lipman)...
2     Newsgroup: comp.os.ms-windows.misc document_id...
3     Newsgroup: comp.sys.ibm.pc.hardware document_i...
4     Newsgroup: comp.sys.mac.hardware document_id: ...
5     Newsgroup: comp.windows.x document_id: 64830 F...
6     Newsgroup: misc.forsale document_id: 70337 Fro...
7     Newsgroup: rec.autos document_id: 101551 From:...
8     Newsgroup: rec.motorcycles document_id: 101725...
9     Newsgroup: rec.sport.baseball document_id: 100...
10    Newsgroup: rec.sport.hockey document_id: 52550...
11    Newsgroup: sci.crypt document_id: 14147 From: ...
12    Newsgroup: sci.electronics document_id: 52434 ...
13    Newsgroup: sci.med document_id: 57110 From: be...
14    Newsgroup: sci.space document_id: 59497 From: ...
15    Newsgroup: soc.religion.christian document_id:...
16    Newsgroup: talk.politics.guns document_id: 532...
17    Newsgroup: talk.politics.mideast document_

In [7]:
testing

category                                           articles
0  rec.sport.baseball  Becoming a better basketball player is not jus...
1           sci.space  By Maria Temming March 24, 2021 at 10:00 am As...

In [8]:
testing['articles']

0    Becoming a better basketball player is not jus...
1    By Maria Temming March 24, 2021 at 10:00 am As...
Name: articles, dtype: object

# MODEL

In [9]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense, Input, GlobalMaxPooling1D
from tensorflow.keras.layers import LSTM,Embedding
from tensorflow.keras.models import Model

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [10]:
dataframe['b_labels']=dataframe['category'].map({"alt.atheism":0,"comp.graphics":1,"comp.os.ms-windows.misc":2,"comp.sys.ibm.pc.hardware":3,
                "comp.sys.mac.hardware":4,"comp.windows.x":5,"misc.forsale":6,"rec.autos":7,"rec.motorcycles":8,
                "rec.sport.baseball":9,"rec.sport.hockey":10,"sci.crypt":11,"sci.electronics":12,"sci.med":13,
                "sci.space":14,"soc.religion.christian":15,"talk.politics.guns":16,"talk.politics.mideast":17,
                "talk.politics.misc":18,"talk.religion.misc":19})
Y=dataframe['b_labels'].values

In [11]:
testing['b_labels']=testing['category'].map({"rec.sport.baseball":9,"sci.space":14,"talk.politics.mideast":17})

In [12]:
dataframe

category  \
0                alt.atheism   
1              comp.graphics   
2    comp.os.ms-windows.misc   
3   comp.sys.ibm.pc.hardware   
4      comp.sys.mac.hardware   
5             comp.windows.x   
6               misc.forsale   
7                  rec.autos   
8            rec.motorcycles   
9         rec.sport.baseball   
10          rec.sport.hockey   
11                 sci.crypt   
12           sci.electronics   
13                   sci.med   
14                 sci.space   
15    soc.religion.christian   
16        talk.politics.guns   
17     talk.politics.mideast   
18        talk.politics.misc   
19        talk.religion.misc   

                                             articles  b_labels  
0   From: mathew <mathew@mantis.co.uk> Subject: Al...         0  
1   From: lipman@oasys.dt.navy.mil (Robert Lipman)...         1  
2   Newsgroup: comp.os.ms-windows.misc document_id...         2  
3   Newsgroup: comp.sys.ibm.pc.hardware document_i...         3  
4   Newsgroup: comp.sys.mac.hardware document_id: ...         4  
5   Newsgroup: comp.windows.x document_id: 64830 F...         5  
6   Newsgroup: misc.forsale document_id: 70337 Fro...         6  
7   Newsgroup: rec.autos document_id: 101551 From:...         7  
8   Newsgroup: rec.motorcycles document_id: 101725...         8  
9   Newsgroup: rec.sport.baseball document_id: 100...         9  
10  Newsgroup: rec.sport.hockey document_id: 52550...        10  
11  Newsgroup: sci.crypt document_id: 14147 From: ...        11  
12  Newsgroup: sci.electronics document_id: 52434 ...        12  
13  Newsgroup: sci.med document_id: 57110 From: be...        13  
14  Newsgroup: sci.space document_id: 59497 From: ...        14  
15  Newsgroup: soc.religion.christian document_id:...        15  
16  Newsgroup: talk.politics.guns document_id: 532...        16  
17  Newsgroup: talk.politics.mideast document_id: ...        17  
18  Newsgroup: talk.politics.misc document_id: 124...        18  
19  Newsgroup: talk.religion.misc document_id: 827...        19

In [13]:
Y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [14]:
MAX_VOCAB_SIZE=200000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)

In [15]:
tokenizer.fit_on_texts(dataframe['articles'])

In [16]:
sequence_train=tokenizer.texts_to_sequences(dataframe['articles'])
sequence_test=tokenizer.texts_to_sequences(testing['articles'])

In [17]:
word2idx=tokenizer.word_index
V=len(word2idx)
print("Found %s unique tokens." %V)

Found 190934 unique tokens.


In [18]:
data_train=pad_sequences(sequence_train)
print("Shape of data train tensor: ",data_train.shape)
T=data_train.shape[1]

Shape of data train tensor:  (20, 1002124)


In [19]:
data_test=pad_sequences(sequence_test,maxlen=T)
print("Shape of data test tensor: ",data_test.shape)


Shape of data test tensor:  (2, 1002124)


In [20]:
D=20
M=15
i=Input(shape=(T,))
x=Embedding(V+1,D)(i)
x=LSTM(M,return_sequences=True)(x)
x=GlobalMaxPooling1D()(x)
x=Dense(20,activation='softmax')(x)
model=Model(i,x)

In [21]:
model.compile(
        loss='sparse_categorical_crossentropy',
optimizer='adam',
metrics=['accuracy'])



In [22]:
Ytest=testing['b_labels'].values

In [23]:
data_train

array([[    0,     0,     0, ..., 11974,  7424, 27198],
       [    0,     0,     0, ...,   207,     6,   716],
       [   31,   119,   348, ...,    16,   177,   207],
       ...,
       [    0,     0,     0, ...,   488, 16825, 14402],
       [    0,     0,     0, ...,  8629, 14609,   985],
       [    0,     0,     0, ...,     3,     1,  1663]])

In [24]:
Y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [25]:
data_test

array([[  0,   0,   0, ...,   1, 367, 659],
       [  0,   0,   0, ...,  77, 183, 588]])

In [26]:
Ytest

array([ 9, 14], dtype=int64)

In [27]:
pd.DataFrame(data_train).to_csv('news.csv')

In [ ]:
print("Training model....")
r=model.fit(
data_train,
Y,
epochs=5,
validation_data=(data_test,Ytest))

Training model....
Epoch 1/5


# PLOTS

In [ ]:
import matplotlib.pyplot as plt
plt.plot(r.history['loss'], label='loss')
plt.plot(r.history['val_loss'], label='val_loss')
plt.legend()

In [ ]:
# Plot accuracy per iteration
plt.plot(r.history['accuracy'], label='acc')
plt.plot(r.history['val_accuracy'], label='val_acc')
plt.legend()

# SAVING THE MODEL